name: prueba de github actions

on:
  pull_request:
    branches: '*'

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm i -g mocha && npm i chai && npm run test
